food/urls.py
from django.urls import path
from food.views import show_menu, add_food, get_food, get_food_by_id, filter_food, food_detail, edit_food, delete_food, create_food_flutter, edit_food_flutter


app_name = 'food'

urlpatterns = [
    path('', show_menu, name='show_menu'),  # Updated line
    path('get_food/', get_food, name='get_food'),
    path('get_food/<int:id>/', get_food_by_id, name='get_food_by_id'),
    path('add_food/', add_food, name='add_food'),
    path('filter_food/', filter_food, name='filter_food'),
    path('<int:food_id>/', food_detail, name='food_detail'),
    path('edit_food/<int:id>/', edit_food, name='edit_food'),
    path('delete_food/<int:id>/', delete_food, name='delete_food'),
    path('create-flutter/', create_food_flutter, name='create_food_flutter'),
    path('edit-flutter/<int:id>/', edit_food_flutter, name='edit_food_flutter'),
]

forum/urls.py
from django.urls import path
from .views import ThreadListView, ThreadDetailView, CreateThreadView, CreatePostView, add_post, create_post_ajax, delete_thread, delete_post, create_thread_ajax, edit_thread, edit_post, thread_list,show_json, show_post_json, create_post_flutter, edit_post_flutter, edit_thread_flutter, delete_post_flutter, delete_thread_flutter

app_name = 'forum'

urlpatterns = [
    path('', ThreadListView.as_view(), name='thread_list'),
    path('<int:pk>/', ThreadDetailView.as_view(), name='thread_detail'),
    path('create/', CreateThreadView.as_view(), name='create_thread'),
    path('<int:pk>/create_post/', CreatePostView.as_view(), name='create_post'),
    path('add_post/', add_post, name='add_post'),  # Endpoint for adding posts via API
    path('create_post_ajax/<int:thread_id>/', create_post_ajax, name='create_post_ajax'),
    path('<int:pk>/delete_thread/', delete_thread, name='delete_thread'),
    path('<int:pk>/delete_post/', delete_post, name='delete_post'),
    path('create_thread_ajax/', create_thread_ajax, name='create_thread_ajax'),
    # New routes for thread management
    path('threads/<int:thread_id>/edit/', edit_thread, name='edit_thread'),
    path('threads/<int:thread_id>/delete/', delete_thread, name='delete_thread'),

    # New routes for post management
    path('posts/<int:post_id>/edit/', edit_post, name='edit_post'),
    path('posts/<int:post_id>/delete/', delete_post, name='delete_post'),\
    path('threads/', thread_list, name='thread_list'),
    path('threads/json/', show_json, name='show_json'),
    path('threads/<int:thread_id>/json/', show_post_json, name='show_post_json'),

    path('create-post-flutter/', create_post_flutter, name='create_post_flutter'),
    path('edit-post-flutter/<int:post_id>/', edit_post_flutter, name='edit_post_flutter'),
    path('edit-thread-flutter/<int:thread_id>/', edit_thread_flutter, name='edit_thread_flutter'),
    path('delete-post-flutter/<int:post_id>/', delete_post_flutter, name='delete_post_flutter'),
    path('delete-thread-flutter/<int:thread_id>/', delete_thread_flutter, name='delete_thread_flutter'),
]

halal_bites/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import show_main
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('admin/', admin.site.urls),
    path('tracker/', include(('tracker.urls', 'tracker'), namespace='tracker')),
    path('menu/', include('food.urls')),
    path('rating/', include('rating.urls')),
    path('auth/', include('authentication.urls')),
    path('resto/', include('resto.urls')),
    path('home/', show_main, name='home'),
    path('forum/', include('forum.urls')),
]

rating/urls.py
from django.urls import path
from rating.views import create_rating, rated_foods, show_json, show_xml, create_rating_flutter, edit_rating, delete_rating, edit_rating_flutter, delete_rating_flutter
from .views import get_rating_ajax, edit_rating_ajax, delete_rating_ajax, rated_foods

app_name = 'rating'

urlpatterns = [
    path('rate/<int:food_id>/', create_rating, name='create_rating'),
    path('rated-foods/', rated_foods, name='rated_foods'),
    path('json/', show_json, name='get_json'),
    path('xml/', show_xml, name='get_xml'),
    path('create_rating_flutter/', create_rating_flutter, name='create_rating_flutter'),
    path('edit-rating/<uuid:rating_id>/', edit_rating, name='edit_rating'),
    path('delete-rating/<uuid:rating_id>/', delete_rating, name='delete_rating'),
    path('edit-rating-flutter/<uuid:rating_id>/', edit_rating_flutter, name='edit_rating_flutter'),
    path('delete-rating-flutter/<uuid:rating_id>/', delete_rating_flutter, name='delete_rating_flutter'),
    path('get_rating_ajax/<uuid:rating_id>/', get_rating_ajax, name='get_rating_ajax'),
    path('edit_rating_ajax/', edit_rating_ajax, name='edit_rating_ajax'),
    path('delete_rating_ajax/', delete_rating_ajax, name='delete_rating_ajax'),
]

resto/urls.py
from django.urls import path
from resto.views import get_resto, show_resto, filter_resto, add_resto
from resto.views import delete_resto, resto_detail, show_json, get_resto, show_xml
from resto.views import create_resto_flutter, get_csrf_token, edit_resto_flutter
from django.contrib.auth.decorators import login_required



app_name = "resto"

urlpatterns = [
    path('get-resto/', get_resto, name='get_resto'), 
    path('', login_required(show_resto, login_url='/auth/login'), name='show_resto'),
    path('filter-resto/', filter_resto, name='filter_resto'),
    path('add-resto/', add_resto, name='add_resto'),
    path('delete-resto/<int:id>/', delete_resto, name="delete_resto"),
    path('detail/<int:pk>/', resto_detail, name="resto_detail"),
    path('json/', show_json, name='show_json'), 
    path('xml/', show_xml, name='show_xml'),
    path('create-flutter/', create_resto_flutter, name="create_resto_flutter"),
    path('get-csrf-token/', get_csrf_token, name='get_csrf_token'),
    path('edit-flutter/<int:id>/', edit_resto_flutter, name='edit_resto_flutter'),
]

tracker/urls.py
from django.urls import path
from . import views

app_name = 'tracker'

urlpatterns = [
    path('food_tracker', views.food_tracker, name='food_tracker'),
    path('json/', views.show_json, name='show_json'),
    path('add/', views.add_tracker, name='add_tracker'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<meta name="viewport" content="width=device-width,initial-scale=1"
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block meta %}{% endblock meta %}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<style>
    .center-container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        width: 100%;
    }

    .center-content {
        max-width: 1000px; /* max-width is adjustable */
        width: 100%;
    }
</style>
<body class="bg-gray-100 min-h-screen flex flex-col">
    {% include "navbar.html" %}
    {% block content %}
    {% endblock content %}
    {% include "footer.html" %}
    {% block script %}
    {% endblock script %}
</body>
</html>

templates/navbar.html
<!-- Navbar -->
<nav class="bg-white shadow-lg sticky top-0 left-0 z-40 w-screen">
    <div class="max-w-7xl mx-auto px-4">
        <div class="flex justify-between items-center">
            <div class="flex items-center space-x-4">
                <!-- Logo -->
                <div>
                    <a href="{% url 'home' %}" class="flex items-center py-5 px-2 text-yellow-500">
                        <span class="font-bold text-2xl">HalalBites</span>
                    </a>
                </div>
                <!-- Primary Nav -->
                <div class="hidden md:flex items-center space-x-1">
                    <a href="{% url 'resto:show_resto' %}" class="py-5 px-3 text-gray-700 hover:text-yellow-500">Resto</a>
                    <a href="{% url 'food:show_menu' %}" class="py-5 px-3 text-gray-700 hover:text-yellow-500">Menu</a>
                    <a href="{% url 'tracker:food_tracker' %}" class="py-5 px-3 text-gray-700 hover:text-yellow-500">Food Tracker</a>
                    <a href="{% url 'forum:thread_list' %}" class="py-5 px-3 text-gray-700 hover:text-yellow-500">Forum</a>
                    <a href="{% url 'rating:rated_foods' %}" class="py-5 px-3 text-gray-700 hover:text-yellow-500">Review</a>
                </div>

            </div>
            <!-- Secondary Nav -->
            <div class="hidden md:flex items-center space-x-1">
                <a href="{% url 'logout' %}" class="py-5 px-3 text-gray-700 hover:text-yellow-500">Logout</a>
            </div>

            <!-- Hamburger Icon -->
            <div class="md:hidden">
                <button id="hamburger" class="flex flex-col items-center justify-center w-10 h-10 rounded focus:outline-none">
                    <span class="block w-8 h-1 bg-yellow-500 mb-1"></span>
                    <span class="block w-8 h-1 bg-yellow-500 mb-1"></span>
                    <span class="block w-8 h-1 bg-yellow-500"></span>
                </button>
            </div>
        </div>
        <!-- Mobile Menu -->
        <div id="menu" class="hidden md:hidden mt-2">
            <div class="flex flex-col space-y-1">
                <a href="{% url 'resto:show_resto' %}" class="block py-2 px-3 text-gray-700 bg-gray-100 rounded hover:bg-yellow-500 hover:text-white">Resto</a>
                <a href="{% url 'tracker:food_tracker' %}" class="block py-2 px-3 text-gray-700 bg-gray-100 rounded hover:bg-yellow-500 hover:text-white">Food Tracker</a>
                <a href="#" class="block py-2 px-3 text-gray-700 bg-gray-100 rounded hover:bg-yellow-500 hover:text-white">Review</a>
                <a href="{% url 'logout' %}" class="block py-2 px-3 text-gray-700 bg-gray-100 rounded hover:bg-yellow-500 hover:text-white">Logout</a>
            </div>
        </div>
    </div>
</nav>

<script>
    const hamburger = document.getElementById('hamburger');
    const menu = document.getElementById('menu');

    hamburger.addEventListener('click', () => {
        menu.classList.toggle('hidden');
    });
</script>